language: php
php:
  - 7.1
  - 7.2
  - 7.3
before_script:
  - sudo apt-get install redis-server
  - sudo service redis-server start
  - sudo apt-get install memcached
  - sudo service memcached start
  - sudo apt-get install libmemcache-dev
  - wget https://pecl.php.net/get/memcached-3.1.3.tgz
    && tar zfvx memcached-3.1.3.tgz
    && cd memcached-3.1.3 
    && phpize
    && ./configure --disable-memcached-sasl
    && make
    && sudo make install
    && cd ..
  - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - git clone https://github.com/websupport-sk/pecl-memcache.git
    && cd pecl-memcache
    && phpize
    && ./configure
    && make
    && sudo make install
    && cd ..
  - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - wget https://pecl.php.net/get/redis-4.1.0.tgz
    && tar zfvx redis-4.1.0.tgz
    && cd redis-4.1.0
    && phpize
    && ./configure
    && make
    && sudo make install
    && cd ..
  - echo "extension=redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev
  - cd tests
script: 
  - ../vendor/bin/phpunit -v
after_script:
  - cd ..
  - travis_retry vendor/bin/php-coveralls -x tests/report/clover.xml -o tests/report/coveralls.json -v